#!/usr/bin/env python

import unittest
import codon_degeneracy


class Tests(unittest.TestCase):
    def test_site_degeneracy(self):
        res = codon_degeneracy._site_degeneracy(["CGU", "CGC", "CGA", "CGG", "AGA", "AGG"])

        self.assertTrue(all(i in res for i in [2, 0]))
        self.assertTrue(all(e in res[2] for e in [
            {'AGG', 'AGA'},
            {'CGA', 'CGU', 'CGG', 'CGC'}]))
        self.assertTrue(all(e in res[0] for e in [
            {'AGA', 'CGA'}, {'CGG', 'AGG'}]))

    def test_sub_rate_gapless(self):
        seq_a = (
            "ATACCCATGGCCAACCTCCTACTCCTCATTGTACCCATTC"
            "TAATCGCAATGGCATTCCTAATGCTTACCGAACGA")
        seq_b = (
            "ATGACCACAGTAAATCTCCTACTTATAATCATACCCACAT"
            "TAGCCGCCATAGCATTTCTCACACTCGTTGAACGAT")
        subrate, _, = codon_degeneracy.substitutions_per_ffds(
            seq_a, seq_b,
            "Vertebrate Mitochondrial", "Vertebrate Mitochondrial")
        self.assertEqual(subrate, (4, 10))

    def test_sub_rate_gapped(self):
        seq_a = "ATGGTATTTTTTACATGCAATGCATGTGGTGAATCAGTGAAGAAAATACAAGTGGAAAAGCATGTGTCTGTTTGCAGAAACTGTGAATGCCTTTCTTGCATTGACTGCGGTAAAGATTTCTGGGGCGATGACTATAAAAACCACGTGAAATGCATAAGTGAAGATCAGAAGTATGGTGGCAAAGGCTATGAAGGTAAAACCCACAAAGGCGACATCAAACAGCAGGCGTGGATTCAGAAAATTAGTGAATTAATAAAGAGACCCAATGTCAGCCCCAAAGTGAGAGAACTTTTAGAGCAAATTAGTGCTTTTGACAACGTTCCCAGGAAAAAGGCAAAATTTCAGAATTGGATGAAGAACAGTTTAAAAGTTCATAATGAATCCATTCTGGACCAGGTGTGGAATATCTTTTCTGAAGCTTCCAACAGCGAACCAGTCAATAAGGAACAGGATCAACGGCCACTCCACCCAGTGGCAAATCCACATGCAGAAATCTCCACCAAGGTTCCAGCCTCCAAAGTGAAAGACGCCGTGGAACAGCAAGGGGAGGTGAAGAAGAATAAAAGAGAAAGAAAGGAAGAACGGCAGAAGAAAAGGAAAAGAGAAAAGAAAGAACTAAAGTTAGAAAACCACCAGGAAAACTCAAGGAATCAGAAGCCTAAGAAGCGCAAAAAGGGACAGGAGGCTGACCTTGAGGCTGGTGGGGAGGAAGTCCCTGAGGCCAATGGCTCTGCAGGGAAGAGGAGCAAGAAGAAGAAGCAGCGCAAGGACAGCGCCAGTGAGGAAGAGGCACGCGTGGGCGCAGGGAAGAGGAAGCGGAGGCACTCGGAAGTTGAAACAGATTCTAAGAAGAAAAAGATGAAGCTCCCAGAGCATCCTGAGGGCGGAGAACCAGAAGACGATGAGGCTCCTGCAAAAGGTAAATTCAACTGGAAGGGAACTATTAAAGCAATTCTGAAACAGGCCCCAGACAATGAAATAACCATCAAAAAGCTAAGGAAAAAGGTTTTAGCTCAGTACTACACAGTGACAGATGAGCATCACAGATCCGAAGAGGAACTCCTGGTCATCTTTAACAAGAAAATCAGCAAGAACCCTACCTTTAAGTTATTAAAGGACAAAGTCAAGCTTGTGAAATGA"
        seq_b = "ATGGTATTTTTTACATGCAATGCATGTGGTGAATCAGTGAAGAAAGTACAAGTGGAAAAGCACGTGGCTGTTTGCAGAAACTGTGAATGCCTGTCTTGCATGGACTGTGGTAAAGATTTCTGGGGTGATGACTACAACCACCATGTGAAGTGCATCAGTGAAGAACAAAAGTACGGTGGCAAAGGTTATGAAGGTAAAACCCACAAAGGTGATGTTATCCTGTTGCAGGCACGGATTCAGAAAATTAATGAATTAATAAAAAGACCCAATGTCAGCCCCAAAGTGAGGGAACTTTTAGAGCAAATTAGTGGTTTTGACAACGTTCCCAGGAAAAGGGCAAAATTTCAGAACTGGAAGAAGAACAGTTTAAAAGTCCATAATGAATCTGTTCTGGAGCAGGTGTGGAATATCTTTTCTGAAGCTTCCAGCAACGAAGCGGTCAGTAAGGGTCAAGCCCAGCAGCCACTCGCCCAGGTGGCCAGCCCGCCCCGCGCAGAGCTCTCTGCCCAGGTTCTAGCCGTTGGAACAAATGACCCCACAGAAAAGCAAGCAGAGGTAAAGAAGAATAAAAGAGAAAGGAAGGAAGAAAGGCAGAAGAATAGAAAGAAGGAGAAGAAAGAACTAAAATTAGAAAACCCCCAAGAGAATTCGAAAGGTCAGAAGCCTAAGAAGCGCAAAACAGGCCAGGAGGCCGGAGAGGAGGCCCCTGCCTCCGCAGGGAAGAGCAGCCAGAGCAAGGCGGGTGAGGCCAAGGGAGCCGCTGACAGAGCTGAGGAGGGAGAGGCCGAGGAGTCCAGGAAAGCCCGGCCTGGGAAGAGAAAGCAGAAGCACTCGGAAGATGACATAGAGTCTAAGAAGAAAAAGGACCACGAATCTCCTGCAAAAGAAAGGATTGCTGCCACCCGTATGGGTGTAGTGCTAGTCATTGATCAACCACGATTTATCAATAAGAATGATAATATTTAG"
        subrate, _, = codon_degeneracy.substitutions_per_ffds(
            seq_a, seq_b)
        self.assertEqual(subrate, (23, 86))

    def test_sub_rate_per_cpg_gapped(self):
        seq_a = "ATGGTATTTTTTACATGCAATGCATGTGGTGAATCAGTGAAGAAAATACAAGTGGAAAAGCATGTGTCTGTTTGCAGAAACTGTGAATGCCTTTCTTGCATTGACTGCGGTAAAGATTTCTGGGGCGATGACTATAAAAACCACGTGAAATGCATAAGTGAAGATCAGAAGTATGGTGGCAAAGGCTATGAAGGTAAAACCCACAAAGGCGACATCAAACAGCAGGCGTGGATTCAGAAAATTAGTGAATTAATAAAGAGACCCAATGTCAGCCCCAAAGTGAGAGAACTTTTAGAGCAAATTAGTGCTTTTGACAACGTTCCCAGGAAAAAGGCAAAATTTCAGAATTGGATGAAGAACAGTTTAAAAGTTCATAATGAATCCATTCTGGACCAGGTGTGGAATATCTTTTCTGAAGCTTCCAACAGCGAACCAGTCAATAAGGAACAGGATCAACGGCCACTCCACCCAGTGGCAAATCCACATGCAGAAATCTCCACCAAGGTTCCAGCCTCCAAAGTGAAAGACGCCGTGGAACAGCAAGGGGAGGTGAAGAAGAATAAAAGAGAAAGAAAGGAAGAACGGCAGAAGAAAAGGAAAAGAGAAAAGAAAGAACTAAAGTTAGAAAACCACCAGGAAAACTCAAGGAATCAGAAGCCTAAGAAGCGCAAAAAGGGACAGGAGGCTGACCTTGAGGCTGGTGGGGAGGAAGTCCCTGAGGCCAATGGCTCTGCAGGGAAGAGGAGCAAGAAGAAGAAGCAGCGCAAGGACAGCGCCAGTGAGGAAGAGGCACGCGTGGGCGCAGGGAAGAGGAAGCGGAGGCACTCGGAAGTTGAAACAGATTCTAAGAAGAAAAAGATGAAGCTCCCAGAGCATCCTGAGGGCGGAGAACCAGAAGACGATGAGGCTCCTGCAAAAGGTAAATTCAACTGGAAGGGAACTATTAAAGCAATTCTGAAACAGGCCCCAGACAATGAAATAACCATCAAAAAGCTAAGGAAAAAGGTTTTAGCTCAGTACTACACAGTGACAGATGAGCATCACAGATCCGAAGAGGAACTCCTGGTCATCTTTAACAAGAAAATCAGCAAGAACCCTACCTTTAAGTTATTAAAGGACAAAGTCAAGCTTGTGAAATGA"
        seq_b = "ATGGTATTTTTTACATGCAATGCATGTGGTGAATCAGTGAAGAAAGTACAAGTGGAAAAGCACGTGGCTGTTTGCAGAAACTGTGAATGCCTGTCTTGCATGGACTGTGGTAAAGATTTCTGGGGTGATGACTACAACCACCATGTGAAGTGCATCAGTGAAGAACAAAAGTACGGTGGCAAAGGTTATGAAGGTAAAACCCACAAAGGTGATGTTATCCTGTTGCAGGCACGGATTCAGAAAATTAATGAATTAATAAAAAGACCCAATGTCAGCCCCAAAGTGAGGGAACTTTTAGAGCAAATTAGTGGTTTTGACAACGTTCCCAGGAAAAGGGCAAAATTTCAGAACTGGAAGAAGAACAGTTTAAAAGTCCATAATGAATCTGTTCTGGAGCAGGTGTGGAATATCTTTTCTGAAGCTTCCAGCAACGAAGCGGTCAGTAAGGGTCAAGCCCAGCAGCCACTCGCCCAGGTGGCCAGCCCGCCCCGCGCAGAGCTCTCTGCCCAGGTTCTAGCCGTTGGAACAAATGACCCCACAGAAAAGCAAGCAGAGGTAAAGAAGAATAAAAGAGAAAGGAAGGAAGAAAGGCAGAAGAATAGAAAGAAGGAGAAGAAAGAACTAAAATTAGAAAACCCCCAAGAGAATTCGAAAGGTCAGAAGCCTAAGAAGCGCAAAACAGGCCAGGAGGCCGGAGAGGAGGCCCCTGCCTCCGCAGGGAAGAGCAGCCAGAGCAAGGCGGGTGAGGCCAAGGGAGCCGCTGACAGAGCTGAGGAGGGAGAGGCCGAGGAGTCCAGGAAAGCCCGGCCTGGGAAGAGAAAGCAGAAGCACTCGGAAGATGACATAGAGTCTAAGAAGAAAAAGGACCACGAATCTCCTGCAAAAGAAAGGATTGCTGCCACCCGTATGGGTGTAGTGCTAGTCATTGATCAACCACGATTTATCAATAAGAATGATAATATTTAG"
        subrates = codon_degeneracy.substitutions_per_ffds_by_cpg_context(
            seq_a, seq_b)
        self.assertEqual(
            subrates,
            {'nonCpG': [8, 34], 'postC': [3, 17],
             'preG': [4, 14], 'postCpreG': [2, 9]})


if __name__ == '__main__':
    unittest.main()
