#!/usr/bin/env python

import unittest
import ffdd.ffdd as ffdd


class Tests(unittest.TestCase):
    def test_site_degeneracyy(self):
        res = {
            site: groups
            for site, groups
            in ffdd._site_degeneracy(
                ["CGU", "CGC", "CGA", "CGG", "AGA", "AGG"])}

        self.assertTrue(all(i in res for i in [2, 0]))
        self.assertTrue(all(e in res[2] for e in [
            {'AGG', 'AGA'},
            {'CGA', 'CGU', 'CGG', 'CGC'}]))
        self.assertTrue(all(e in res[0] for e in [
            {'AGA', 'CGA'}, {'CGG', 'AGG'}]))


if __name__ == '__main__':
    unittest.main()

#     seq_a = (
#     "ATACCCATGGCCAACCTCCTACTCCTCATTGTACCCATTCTAATCGCAATGGCATTCCTAATGCTTACCGAACGA"
#     "AAAATTCTAGGCTATATACAACTACGCAAAGGCCCCAACGTTGTAGGCCCCTACGGGCTACTACAACCCTTCGCT"
#     "GACGCCATAAAACTCTTCACCAAAGAGCCCCTAAAACCCGCCACATCTACCATCACCCTCTACATCACCGCCCCG"
#     "ACCTTAGCTCTCACCATCGCTCTTCTACTATGAACCCCCCTCCCCATACCCAACCCCCTGGTCAACCTCAACCTA"
#     "GGCCTCCTATTTATTCTAGCCACCTCTAGCCTAGCCGTTTACTCAATCCTCTGATCAGGGTGAGCATCAAACTCA"
#     "AACTACGCCCTGATCGGCGCACTGCGAGCAGTAGCCCAAACAATCTCATATGAAGTCACCCTAGCCATCATTCTA"
#     "CTATCAACATTACTAATAAGTGGCTCCTTTAACCTCTCCACCCTTATCACAACACAAGAACACCTCTGATTACTC"
#     "CTGCCATCATGACCCTTGGCCATAATATGATTTATCTCCACACTAGCAGAGACCAACCGAACCCCCTTCGACCTT"
#     "GCCGAAGGGGAGTCCGAACTAGTCTCAGGCTTCAACATCGAATACGCCGCAGGCCCCTTCGCCCTATTCTTCATA"
#     "GCCGAATACACAAACATTATTATAATAAACACCCTCACCACTACAATCTTCCTAGGAACAACATATGACGCACTC"
#     "TCCCCTGAACTCTACACAACATATTTTGTCACCAAGACCCTACTTCTAACCTCCCTGTTCTTATGAATTCGAACA"
#     "GCATACCCCCGATTCCGCTACGACCAACTCATACACCTCCTATGAAAAAACTTCCTACCACTCACCCTAGCATTA"
#     "CTTATATGATATGTCTCCATACCCATTACAATCTCCAGCATTCCCCCTCAAACCTA")

# seq_b = (
#     "ATGACCACAGTAAATCTCCTACTTATAATCATACCCACATTAGCCGCCATAGCATTTCTCACACTCGTTGAACGA"
#     "AAATTACTAGGCCACATGCAACTACGAAAAGGGCCCAATATTGTAGGTCCATGCGGACTATTACAACCCTTCGCC"
#     "GATGCCGTAAAACTTTTCACTAAAGAACCCCTGAAACCCGCAACATCTACCACCATCCTCTATGTCGTCGCACCT"
#     "GCTCTAGCCTTCTTCATTGCCCTCCTCCTATGAACCCCCCTCCCCATACCCAACGCTCTAATCAACTTCAACCTA"
#     "GGGCTCCTATTCATCCTAGCCATACTCAGCCTAATTGTCTACTCCATCCTATGATCAGGATGAGCATCAAACTCA"
#     "AACTACGCCCTAATCGGAGCTCTGCGAGCCGTCGCCCAAACAATTTCATATGAAGTCACCCTTACTATTATCCTC"
#     "CTATCAGTCCTACTAATAAGCGGCTCATTTAACCTTAACACACTCATTACAACGCAAGAGCATCTATGACTCCTC"
#     "CTACCATCATGACCCCTAGCCATAATATGATTTACCTCCACACTAGCAGAAACAAACCGAACCCCTTTTGATCTC"
#     "ATAGAGGGCGAATCAGAATTAGTATCAGGCTTCAACATTGAATACGCCGCAGGTCCATTCGCCCTATTCTTCATA"
#     "GCCGAATACACAAACATCATCATAATAAACGCCCTAACAACCACAATCTTCCTAGGCACATCCCACTCCACTTAT"
#     "TCACCAGAACTATTCACAACATGCTTCGCCACCAAAACACTCTTCCTAACCTCCCTATTCCTATGAATCCGGGCA"
#     "GCATACCCCCGATTCCGTTACGACCAACTTATACACCTACTATGAAAAAACTTCCTCCCCCTCACACTAGCACTA"
#     "CTCATATGATCCACCTCAATACCCATCGCAATCTCCAGCATTCCCCCTCAAACCT")

# # print(ffdd.substitution_rate_at_ffds(seq_a, seq_b))
# print(ffdd.substitution_rate_at_ffds(seq_a, seq_b, "Vertebrate Mitochondrial", "Vertebrate Mitochondrial"))
